// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package service

// Injectors from wire.go:

func BuildInjector(configFile string) (*Injector, func(), error) {
	config, err := NewConfig(configFile)
	if err != nil {
		return nil, nil, err
	}
	timedTask := NewTimedTask()
	logger := NewLogger(config)
	injector, err := NewInjector(config, timedTask, logger)
	if err != nil {
		return nil, nil, err
	}
	return injector, func() {
	}, nil
}
