// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package service

// Injectors from wire.go:

func BuildInjector(configFile string) (*Injector, func(), error) {
	config, err := NewConfig(configFile)
	if err != nil {
		return nil, nil, err
	}
	iTask := NewRenewTask()
	logger := NewLogger()
	injector, err := NewInjector(config, iTask, logger)
	if err != nil {
		return nil, nil, err
	}
	return injector, func() {
	}, nil
}
